language: ruby
rvm:
- 2.1.4
- 2.3.1
- 2.3.2
- 2.4
- 2.5.5
- 2.6

before_install:
  # - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  # - gem install -v 1.17.3 bundler
  # - bundle _1.17.3_ install
  - gem install bundler -v '< 2'
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
